[WIP] Updated Sugarizer Tutorial with IntroJS instead of Bootstrap Tour
llaske/sugarizer pull request #1087
Opened 2022-06-21 19:50 UTC by S-kus

Updated Sugarizer tutorial by replacing bootstrap-tour with introJs for step 9.
- For vanillaJs tutorial, I updated the step 9 docs file.
- Added updated images for reference according to introJs tour library.
- For VueJs tutorial, updated step 9 file.
  - In this activity template is already completed for styling, i.e. `SugarTutorial.js` and `activity.css` is almost completed, So set them up according to introJs.
  -  Removed unused bootstrap-tour-related files.
  - As `jquery.min.js` is not useful anymore, so removed it from the template.

2022-06-22 19:03 UTC, S-kus commented
Updated with correct function for filtering the steps.
@llaske  Could you please review it!

2022-06-26 14:21 UTC, llaske commented
The `tutorial_step9_1.png` image should be updated too (old UI).

2022-06-26 14:38 UTC, llaske requested changes

2022-06-26 14:38 UTC, llaske commented on docs/tutorial/VueJS/step9.md
> +> In case you need to download them again, you can find the `introjs.css` and `intro.js` files [here](https://www.jsdelivr.com/package/npm/intro.js). Copy these files in your Pawn activity. The first
Reference locales copies of these files instead of pointing to the repo.

2022-06-26 14:38 UTC, llaske commented on docs/tutorial/VueJS/step9.md
>  TutoPrev=Prev
`TutoEnd` is no longer needed

2022-06-26 14:38 UTC, llaske commented on docs/tutorial/VueJS/step9.md
> +	steps= steps.filter(function (obj) {
I think this filtering stuff could be done in the `SugarTutorial.show` method.

2022-06-26 14:38 UTC, llaske commented on docs/tutorial/VueJS/step9.md
> +Here, we are also ensuring that if any element we are targeting for steps, then it should be present or should be visible to display our step.
No need to be explained if it's done directly in the `SugarTutorial` component.

2022-06-26 14:38 UTC, llaske commented on docs/tutorial/VueJS/step9.md
> +        return ($(obj.element).length && document.querySelector(obj.element) && document.querySelector(obj.element).style.display != 'none') || !('element' in obj);
`$(obj.element)` is a jQuery syntax. It can't be used now.

2022-06-26 14:40 UTC, llaske commented
jquery and bootstrap-tour JS and CSS files should be removed from Vue.js ActivityTemplate directory and replaced by required IntroJs files.

2022-06-26 18:53 UTC, S-kus commented
Hey @llaske, corrected all the changes, could you please review it again.

2022-07-09 19:38 UTC, merged