Replaced bootstrap-tour with introJs tour library in Story Activity
llaske/sugarizer pull request #1093
Opened 2022-08-26 21:26 UTC by abhishek-sultaniya

I have tried to replace bootstrap-tour with introJs tour library in Story Activity.

2022-08-27 17:13 UTC, S-kus commented
Hey @abhishek-sultaniya, Nice try. I have some suggestions for the pull request file changes:
- You should be careful with indentation, exa: [here](https://github.com/llaske/sugarizer/pull/1093/files#diff-5049a0d277250ea21dd23485c1f4eb1a558945122a07995407d25d92060aed97R277-R280)
- Remove the [Commented](https://github.com/llaske/sugarizer/pull/1093/files#diff-d25f0aa22b02a2881580f1a6251ceed827e0d07e22c6e3230dd2afeed2b5d66bR1408-R1410) part.
- You should not add your local `package-lock.json` changes and newly created empty files in your final commit. [this](https://github.com/llaske/sugarizer/pull/1093/files#diff-92f870a9cb19804a510a8ed90d02cbd9fb138534a7252290a3b1f39ed839c645)

@llaske what are your views?

2022-08-27 20:05 UTC, llaske requested changes
Good start.
`sugarizerindex.html` is not related to this PR.
Please send the PR on the dev branch like explained [here](https://github.com/llaske/sugarizer/blob/dev/CONTRIBUTING.md).

2022-08-27 20:05 UTC, llaske commented on activities/Story.activity/index.html
> +	// <script src="lib/jquery.min.js"></script>
Do not leave commented line.
Plus it's not really commented because Javascript comments are not recognized in HTML.

2022-08-27 20:05 UTC, llaske commented on activities/Story.activity/js/activity.js
> +					// element: "",
Remove commented lines

2022-08-27 23:50 UTC, abhishek-sultaniya commented
Hey @llaske ,I made the above changes in the recent commits. Could you please review it again?

2022-08-28 07:57 UTC, llaske commented
Okay but the PR should be on the dev branch, not on the master branch.

2022-08-28 21:22 UTC, abhishek-sultaniya commented
Changed the PR to dev branch.
Is it fine now?

2022-08-30 07:06 UTC, closed without merging

2022-08-30 19:38 UTC, llaske commented
Is there any reason why you closed the issue?
Reopen it if you want a review.

2022-08-31 22:55 UTC, abhishek-sultaniya commented
Yes,I had some problem with last forked PR,so had to fork it again.
Had made a new PR #1096.
Please look at it and review it.