Move Measure Activity to IntroJS
llaske/sugarizer pull request #1102
Opened 2022-09-03 23:25 UTC by EshaanAgg

Fixes: [#1090](https://github.com/llaske/sugarizer/issues/1090)
I have replaced bootstrap-tour with introJs library in Measure Activity.

2022-09-04 18:02 UTC, disha1202 requested changes
This is great 👏🏻 But the tutorial is not working as it should.

[screen-recorder-sun-sep-04-2022-23-30-45.webm](https://user-images.githubusercontent.com/58461801/188327236-5e522032-f837-4ec0-9f54-4103d76b50f2.webm)

And also why have you removed bootstrap.min.css file?

2022-09-04 18:36 UTC, EshaanAgg commented on activities/Measure.activity/index.html
> -			<sugar-toolitem
The changes are probably due to using a different code formatter on my system. I have reverted them back to the original style, and also added back bootstrap.min.css which I earlier removed by mistake.

2022-09-04 18:43 UTC, EshaanAgg commented
Also, there seems to be an error in the original bootstrap.min.css that was present in the repository. 

Original:
<img width="211" alt="image" src="https://user-images.githubusercontent.com/96648934/188328690-100f5dbc-e354-4a7f-beb1-e56b3f972f3e.png">
Edited:
![image](https://user-images.githubusercontent.com/96648934/188328563-cf77f9f5-42d4-43f7-b8c0-ab9e1c66a0a1.png)

Line number 7879 was earlier `background-color: #000\9`, which I have now corrected as shown.

2022-09-04 18:49 UTC, disha1202 commented
Great!! Thanks @EshaanAgg 
Looks good to me 👍🏻

2022-09-06 20:02 UTC, llaske commented
@EshaanAgg the title bar is too small and the close button position is wrong.
It's probably related to IntroJS version see others PR on the issue to find a fix.

![image](https://user-images.githubusercontent.com/981841/188727552-d8cc4304-96d2-4d52-8a47-1e3c7372c1ae.png)

2022-09-07 07:46 UTC, EshaanAgg commented
@llaske Downgraded the version of Introjs.css as recommended in PR #1096. Please review now.

2022-09-07 20:11 UTC, llaske commented
That's fine now but the `test.css` file should not be there, it seems to be a dummy file.

2022-09-07 20:23 UTC, EshaanAgg commented
Removed the same in the new commit.

2022-09-08 19:40 UTC, merged

2022-09-08 19:41 UTC, llaske commented
Nice. Thanks.