Migrated bootstrap-tour to IntroJs in Memorize Activity tutorial
llaske/sugarizer pull request #1158
Opened 2023-01-23 12:03 UTC by shubhangNarain

Hey @llaske, I have migrated Memorize activity tutorial from bootstrap-tour to IntroJs, referring the Issue: #1090.  Please review the PR. Here's a look at the activity tutorial now:
<img width="1666" alt="Screenshot 2023-01-23 at 5 30 39 PM" src="https://user-images.githubusercontent.com/80174035/214034906-6c683200-a3e4-4685-82e4-1651961e41a7.png">

2023-01-24 17:23 UTC, llaske commented on .github/workflows/main.yml
> +<<<<<<< HEAD
You have no reason to change this file.
I guess you've got a merge conflict.

2023-01-25 14:23 UTC, shubhangNarain commented
@llaske I've fixed the merge conflict, please review and tell me if there are any changes. Thanks.

2023-01-28 09:36 UTC, llaske requested changes

2023-01-28 09:36 UTC, llaske commented on .github/workflows/main.yml
> +            git pull
This file must not be updated at all since it's not related to this PR.

2023-01-28 09:36 UTC, llaske commented on activities/Memorize.activity/css/activity.css
> +/* .tutorial-title {
Do not keep commented code.

2023-01-28 09:36 UTC, llaske commented on activities/Memorize.activity/css/activity.css
> +}
Avoid updating space/tab/newlines.

2023-01-28 09:36 UTC, llaske commented on activities/Memorize.activity/index.html
> +</html>
Avoid updating space/tab/newlines.

2023-01-28 09:36 UTC, llaske commented on activities/Memorize.activity/lib/tutorial.js
> +});
Avoid updating space/tab/newlines.

2023-02-06 06:44 UTC, closed without merging