FlipActivity Bootstrap to IntroJS Tour
llaske/sugarizer pull request #1243
Opened 2023-03-03 10:30 UTC by VedantSharma11

hey @llaske 
i have changed bootstrap tour to inrojs js tour in Flipactivity ,pls review it.
Refer to issue:https://github.com/llaske/sugarizer/issues/1090

![image](https://user-images.githubusercontent.com/96445392/222426517-b66ef1a8-9c48-4374-addd-aa8abb40a088.png)

2023-03-03 16:05 UTC, llaske requested changes

2023-03-03 16:05 UTC, llaske commented on activities/Flip.activity/js/activity.js
> +		canvas.height = window.innerHeight-180;
You should not change the canvas size.

2023-03-03 16:05 UTC, llaske commented on activities/Flip.activity/js/activity.js
> +			canvas.height = window.innerHeight-180;
You should not change the canvas size.

2023-03-03 16:08 UTC, VedantSharma11 commented on activities/Flip.activity/js/activity.js
> +			canvas.height = window.innerHeight-180;
@llaske i'll correct it right away!

2023-03-03 16:13 UTC, VedantSharma11 commented
@llaske please review it i have made the changes

2023-03-03 16:15 UTC, llaske commented
@VedantSharma11 only a part of it

2023-03-03 16:33 UTC, VedantSharma11 commented
@llaske fixed it 
but actually i had  changed the canvas size because when the 2nd popup shows up the canvas moves a bit upwards so to fix it i decreased the height which fixed the issue.

pls review

2023-03-04 09:44 UTC, llaske commented
Yes, you're right the move should be fixed.

![image](https://user-images.githubusercontent.com/981841/222891558-ff9be329-f2db-4d47-b207-2092648a870b.png)

But changing the way the activity work is not a good idea. You should explore other ways. May be using some introjs events.

2023-03-04 11:36 UTC, VedantSharma11 commented
@llaske Sure i'll try some other way to fix it instead of changing the canvas size

2023-03-04 13:40 UTC, VedantSharma11 commented
@llaske i have fixed it please review

2023-03-04 22:07 UTC, VedantSharma11 commented
@llaske i have fixed it please review

2023-03-05 09:42 UTC, merged

2023-03-05 09:43 UTC, llaske commented
Good @VedantSharma11 . Thanks.