Replaced WebL10n with i18next in FoodChain activity
llaske/sugarizer pull request #1525
Opened 2024-02-14 10:16 UTC by soham2312

fix issue #1378 

Replaced Code in FoodChain Activity to l10n

@llaske , could you please review it

2024-02-14 20:42 UTC, llaske commented
There is an error on launch of the activity 

![image](https://github.com/llaske/sugarizer/assets/981841/2258fe42-8bf5-45b7-83ab-27003d335b23)

2024-02-15 15:20 UTC, Vishalk91-4 requested changes

2024-02-15 15:20 UTC, Vishalk91-4 commented on activities/FoodChain.activity/lib/sugar-web/activity/activity.js
remove l10n in the function( 

You have removed webL10n but not it's corresponding l10n

2024-02-16 14:38 UTC, soham2312 commented
@llaske sir can you review it

2024-02-16 21:06 UTC, merged

2024-02-16 21:12 UTC, llaske commented
Nice @soham2312, thanks