Replaced WebL10n with i18next in Markdown activity
llaske/sugarizer pull request #1540
Opened 2024-02-27 12:48 UTC by soham2312

fix issue #1378 

Replaced Code in MarkDown Activity to l10n

@llaske  , could you please review it

2024-02-27 21:25 UTC, llaske commented
Could you avoid to change file formatting.
Only updated lines must be changed in files. It's important for maintenance reason.
I guess it's coming from your editor settings.

2024-02-29 02:22 UTC, soham2312 commented
Sure @llaske

2024-02-29 11:52 UTC, soham2312 commented
I have tried to make the changes as much as possible @llaske please review it

2024-03-02 20:58 UTC, llaske requested changes
You still have a lot of indentation change only.
Plus you've got the same issue than this one https://github.com/llaske/sugarizer/pull/1533#issuecomment-1955152552

2024-03-02 20:58 UTC, llaske commented on activities/Markdown.activity/js/activity.js
> -				"wmd-undo-button", "wmd-redo-button", "wmd-showHideEditor-button","wmd-showHidePreview-button"];
Indentation change

2024-03-02 20:58 UTC, llaske commented on activities/Markdown.activity/js/activity.js
> +			datastoreObject.save(function () { });
Indentation change

2024-03-02 20:58 UTC, llaske commented on activities/Markdown.activity/js/activity.js
> +		function isElementHidden(element) {
Indentation change

2024-03-02 20:58 UTC, llaske commented on activities/Markdown.activity/js/activity.js
> +		showHideEditor.onclick = function () {
Indentation change

2024-03-02 20:58 UTC, llaske commented on activities/Markdown.activity/js/activity.js
> +			if (isElementHidden(preview)) {
Identation change

2024-03-02 20:58 UTC, llaske commented on activities/Markdown.activity/js/activity.js
> +			if (isElementHidden(panel)) {
Identation change

2024-03-02 20:58 UTC, llaske commented on activities/Markdown.activity/js/activity.js
> +			else {
Identation change

2024-03-02 20:58 UTC, llaske commented on activities/Markdown.activity/js/activity.js
> +		showHidePreview.onclick = function () {
Identation change

2024-03-02 20:58 UTC, llaske commented on activities/Markdown.activity/js/activity.js
> +			if (isElementHidden(preview)) {
Identation change

2024-03-03 12:39 UTC, soham2312 commented
@llaske Resolved all the indentations mentioned

2024-03-05 20:46 UTC, llaske requested changes
Still indentation change: only lines changed related to the issue must be updated.
Plus the issue regarding fallback language loading should be solved (see https://github.com/llaske/sugarizer/pull/1533#issuecomment-1955152552)

2024-03-05 20:46 UTC, llaske commented on activities/Markdown.activity/js/activity.js
> +		function isElementHidden(element){
Still indentation issue.

2024-03-05 20:46 UTC, llaske commented on activities/Markdown.activity/js/activity.js
> +			if (isElementHidden(preview))
Still indentation issue.

2024-03-05 20:46 UTC, llaske commented on activities/Markdown.activity/js/activity.js
> +			if (isElementHidden(panel))
Still indentation issue.

2024-03-05 20:46 UTC, llaske commented on activities/Markdown.activity/js/activity.js
> +			else {
Still indentation issue.

2024-03-05 20:46 UTC, llaske commented on activities/Markdown.activity/js/activity.js
> +		showHidePreview.onclick = function () {
Still indentation issue.

2024-03-05 20:46 UTC, llaske commented on activities/Markdown.activity/js/activity.js
> +			if (isElementHidden(preview))
Still indentation issue.

2024-03-06 20:45 UTC, merged