FIXED : Display a message when there is no activity matching the search in listview
llaske/sugarizer pull request #1561
Opened 2024-03-14 18:52 UTC by hharshas

2024-03-14 21:18 UTC, llaske requested changes
Lot of code change is not related to the fix: the add of prefix ":".
Please refresh your branch to limit code change to update need for the fix.

2024-03-14 21:18 UTC, llaske commented on v2/js/screens/firstscreen.js
> +									:color="256"
No need to be change.

2024-03-14 21:26 UTC, hharshas commented on v2/js/screens/firstscreen.js
> +									:color="256"
ohk, resolving these.

2024-03-14 21:45 UTC, hharshas reviewed
unnecessary changes have been removed.

2024-03-15 14:45 UTC, llaske commented on v2/js/screens/listview.js
> +						<div> No matching activities </div>
Text must be localized.

2024-03-23 09:38 UTC, hharshas commented
Can you review this again ?

2024-03-23 15:35 UTC, llaske commented
> @llaske Can you review this again ?

Look like nothing has changed since my previous review.

2024-03-23 19:16 UTC, hharshas commented
@llaske I localized the texts as you told. Is there something else that I am missing and I have to do ?

2024-03-23 20:58 UTC, llaske commented
> @llaske I localized the texts as you told me to do. Is there something else that I am missing and I have to do ?

Yes, see comments on the review https://github.com/llaske/sugarizer/pull/1561/files/c87feda844d05640f652382b1d7bbc651addb2d7

2024-03-24 06:46 UTC, hharshas commented
@llaske  I am moving offtrack and unable to understand what to do so here is the summary of all the changes that I have brought.
Motive : Display a message when there is no activity matching the search in listview.
Further Changes  :-
- [x] fix: the add of prefix ":". https://github.com/llaske/sugarizer/pull/1561#pullrequestreview-1937734840 (remove ':')
- [x] Text must be localized. https://github.com/llaske/sugarizer/pull/1561#discussion_r1526401023 (add Sugar.l10n)

Total 6 Files, 60 lines Changed in 9 commits 
Please comment below for further assistant...

2024-03-24 09:12 UTC, llaske requested changes
Sorry @hharshas my review was pending. See my comments above.

2024-03-24 09:48 UTC, hharshas commented
@llaske  Ohk will resolve these...

2024-03-25 05:26 UTC, closed without merging