Fix: vertical bar broken in chart/gear acitivity (issue: #1646)
llaske/sugarizer pull request #1673
Opened 2024-11-21 07:32 UTC by AdityaKrSingh26

Fixed the broken vertical line in Chart/Gears activities, ensuring its applicable on all plaforms (issue: #1646)

Steps:
- Divided the toolbar in two parts left and right, used` dislay: flex` and `justify-content: space-between` to move both the part to ends of both side of screen. and used `dislay: flex` and `align-item:centre` to move hr to correct position.
- Earlier the negative margin was causing the cross platform issue for hr. Removed the negative margin.

### Chrome:
![image](https://github.com/user-attachments/assets/3e8e2c3d-e9df-418a-9014-c8aada2d0957)
![image](https://github.com/user-attachments/assets/2e356d17-cea4-4b04-8dc5-d4a8d0f12572)

### Firefox:
![image](https://github.com/user-attachments/assets/4d9f9fcb-49b4-48f5-be11-33cc7bb58538)
![image](https://github.com/user-attachments/assets/72e267b1-9ad6-40ba-9aa3-fa8fddb97eec)

### Electron.js app:
![image](https://github.com/user-attachments/assets/89456bbd-54f7-466f-bfd4-be939216fe77)
![image](https://github.com/user-attachments/assets/61ef609c-fdc5-4360-a2e3-f2357f6e9840)

2024-11-21 20:42 UTC, llaske requested changes
I guess it's related to your IDE settings but do not change file indentation.
Only lines updated should be in the PR.

2024-11-21 20:42 UTC, llaske commented on activities/Chart.activity/index.html
> +					></sugar-toolitem>
Do not change indentation.

2024-11-21 20:42 UTC, llaske commented on activities/Chart.activity/index.html
> +					<sugar-toolitem id="remove-button" :title="l10n.stringRemoveValue" @click="removeData"></sugar-toolitem>
Do not change indentation.

2024-11-21 20:42 UTC, llaske commented on activities/Chart.activity/lib/sugar-web/graphics/css/sugar-96dpi.css
> +  /* margin-bottom: -17px; */
Do not let commented code.

2024-11-22 03:18 UTC, AdityaKrSingh26 commented
Ok  i will make the changes you mentioned. Thanks

2024-11-22 18:05 UTC, AdityaKrSingh26 commented
Hey @llaske i have removed the comments and indentation in my latest commit please have a look

2024-11-23 21:12 UTC, llaske commented
It works.
You're not supposed to change the library `sugar-96dpi.css` because it's a shared library copied in every activity.
BTW it could be acceptable if it's a minor change. But using `flex` in the toolbar a major change that will impact all activities. Plus split it in left/right has no logical reason. 
Could you find a way to limit the impact to activity css only or to the `hr` element only?

2024-11-24 03:31 UTC, AdityaKrSingh26 commented
I looked around a bit and found out that the issue with <hr/ > lines not being consistent was `margin-bottom : -17px` the negative margin is causing cross platform issue as different browser interpret negative margin differently (please correct me if i am wrong). While` display : flex `property is consistent on all platforms.

I split right/left because on applying display flex the style class of pull-right was over written so to move the icons in group in 2 sides of screen i used `justify-content : space-between`

2024-11-24 03:33 UTC, AdityaKrSingh26 commented
One thing that i can think of is that wrapping <hr/> tag with a <div> tag and apply flex property on parent <div> of <hr/>
Is this fine ?

2024-11-27 21:16 UTC, llaske commented
I understand your fix but I would like a fix where only the CSS `.toolbar hr` need to be updated.
Upgrading HTML and use a `flex` property will change too many files.

2024-12-08 17:41 UTC, AdityaKrSingh26 commented
Hey @llaske .... i looked and tried out diffrent css properties for restricting the changes to `<hr/>` tag only but it seems pretty impossible without changing some properties of the parent tag.

As you mentioned we are not supposed to modify the `sugar-96dpi.css` one thing we can do is add the necessary changes in `acitivity.css` of the specific required files

2024-12-11 21:05 UTC, llaske commented
@AdityaKrSingh26 that's fine if you can limit change to `activity.css`

2024-12-14 06:18 UTC, AdityaKrSingh26 commented
@llaske please have a look at the latest commit.

2024-12-15 21:05 UTC, llaske commented
It works but I'm not a big fan of using flex because it change the look and the behavior of the toolbar.
Why not replace the HR object by a DIV with a vertical border? It will avoid changing the toolbar itself.

2024-12-16 05:53 UTC, AdityaKrSingh26 commented
> It works but I'm not a big fan of using flex because it change the look and the behavior of the toolbar. Why not replace the HR object by a DIV with a vertical border? It will avoid changing the toolbar itself.

Ok i will make the changes

2024-12-16 08:14 UTC, AdityaKrSingh26 commented
> It works but I'm not a big fan of using flex because it change the look and the behavior of the toolbar. Why not replace the HR object by a DIV with a vertical border? It will avoid changing the toolbar itself.

Done. Please have a look

2024-12-18 08:30 UTC, AdityaKrSingh26 commented
@llaske  Done :+1: 
Firefox:
![Screenshot from 2024-12-18 13-57-16](https://github.com/user-attachments/assets/83616906-861e-44a6-b50a-140802f5297d)


Chrome:
![Screenshot from 2024-12-18 13-57-01](https://github.com/user-attachments/assets/bfd021e0-81c0-4dc6-b458-8b35020d0f4c)


Electron:
![Screenshot from 2024-12-18 13-56-34](https://github.com/user-attachments/assets/c60570cc-43ab-4756-99aa-b026b592e521)

2024-12-18 20:48 UTC, merged

2024-12-18 20:49 UTC, llaske commented
Work also on Safari.
Good job, thanks.

2024-12-19 17:48 UTC, AdityaKrSingh26 commented
> Work also on Safari. Good job, thanks.

Finally. :sob: