Solved Issue #903 (Show/hide AM hours,PM hours,minutes)
llaske/sugarizer pull request #910
Opened 2020-12-22 15:02 UTC by sarthak-g

Solved issue #903 

https://user-images.githubusercontent.com/42293606/102902267-c7a10800-4494-11eb-8a00-0708c9eec2cf.mp4

2020-12-22 20:26 UTC, llaske commented
Very good job @sarthak-g. It's cool!

Few remarks:
- The new button should be to the right of the show/hide seconds. It's where all settings button are.
- The settings should be saved in the context so when the activity will be reopen, it will be reopen in the same state

![Peek 22-12-2020 21-20](https://user-images.githubusercontent.com/981841/102929851-a98ad600-449b-11eb-947a-ee671a06af4e.gif)

- One small screens, the Stop button is now invisible. It should always be visible to be able to quit the app.

![Peek 22-12-2020 21-25](https://user-images.githubusercontent.com/981841/102930168-359cfd80-449c-11eb-8830-19bfcfc4a903.gif)

2020-12-23 09:33 UTC, sarthak-g commented
@llaske made suggested changes. Please review.

https://user-images.githubusercontent.com/42293606/102982043-e86a6b80-452f-11eb-97be-3a0ddfe68a3a.mp4

2020-12-25 18:00 UTC, llaske requested changes
Issue on context is now solved.
Regarding responsiveness issue your solution work but it's not the standard solution for Sugarizer activities.

2020-12-25 18:49 UTC, sarthak-g commented on activities/Clock.activity/css/activity.css
> +    width: 36px;
In the latest commit, the hours and minutes display button is hidden for small screen size

2020-12-25 18:49 UTC, sarthak-g commented on activities/Clock.activity/js/activity.js
> +                        if(show_am_pm) document.getElementById("show-am-pm").classList.add("active");
Okay

2020-12-26 20:59 UTC, merged

2020-12-26 21:00 UTC, llaske commented
Very good. Thanks.