Updating markdown files
llaske/sugarizer pull request #938
Opened 2021-03-14 11:35 UTC by ricknjacky

fixes #937

2021-03-14 11:42 UTC, ricknjacky commented
New Behavior: 

![Screenshot (594)](https://user-images.githubusercontent.com/50985033/111067082-6f543200-84e8-11eb-9b41-1f3247acd21d.png)

2021-03-17 19:43 UTC, ricknjacky commented
@llaske please have a look at this and share your thoughts.

2021-03-17 21:57 UTC, llaske commented
@ricknjacky I wonder if there is no a more simple way in Chrome CLI to open a local file using relative path.
Did you try other way to do that? Did you explore CLI options in Chrome? It work in previous version, may be there is another way to do the same.

2021-03-18 07:09 UTC, ricknjacky commented
> @ricknjacky I wonder if there is no a more simple way in Chrome CLI to open a local file using relative path.
> Did you try other way to do that? Did you explore CLI options in Chrome? It work in previous version, may be there is another way to do the same.

There is, we can use `http-server` 
We'd have to install this package accordingly.
`npm install http-server -g`

Now, in the sugarizer directory, to serve it on port 8000, we can type:

`http-server -p 8000`

Should we approach the problem by this method?

2021-03-18 21:11 UTC, llaske commented
No it's worse, it need mean installing an HTTP server.
The idea is to be able to start Sugarizer development just by copying files in a local directory then using a browser and a text editor.

2021-03-19 12:49 UTC, ricknjacky commented
> No it's worse, it mean installing an HTTP server.
> The idea is to be able to start Sugarizer development just by copying files in a local directory then using a browser and a text editor.

I think then, the way proposed above is the correct one.
I say this because, we don't know the directory user is cloning this repo into, hence mentioning the steps accordingly will be correct. What do you think? please share your suggestions.

2021-03-21 10:15 UTC, llaske requested changes
Okay guess that there is no CLI option in Chrome to avoid prefixing with `file:///<Directory>` ?
See my request changes below.

2021-03-21 10:15 UTC, llaske commented on README.md
> + 	chrome --allow-file-access-from-files file:\\\Directory:\sugarizer\index.html
Will be better to write `file:\\\<Directory>\sugarizer\index.html`

2021-03-21 10:15 UTC, llaske commented on README.md
> +Directory in the path above is where you have stored/cloned your sugarizer repo into. Notice the path in the image below to get the gist of it.
Write `<Directory>` instead. This paragraph should be before the one mentioning difference between Windows and Linux/MacOS

2021-03-21 10:15 UTC, llaske commented on README.md
> +In windows, \ is the way path is written and / is the way for Linux/OSX backward and forward slashes differ here, hence path for Linux/MacOS will be:
Write Windows with an uppercase.
Write MacOS instead of OSX.

2021-03-21 10:15 UTC, llaske commented on README.md
> +	chrome --allow-file-access-from-files file:///Directory:/sugarizer/index.html
Write `file:///<Directory>/sugarizer/index.html`.

2021-03-21 10:15 UTC, llaske commented on README.md
> +![](images/Chrome-Sugarizer.png)
The image is useless.

2021-03-21 10:15 UTC, llaske commented on docs/tutorial/VanillaJS/step0.md
> +    chrome --allow-file-access-from-files file:\\\Directory:\sugarizer\index.html
See previous comments.

2021-03-21 10:15 UTC, llaske commented on docs/tutorial/VueJS/step0.md
> +    chrome --allow-file-access-from-files file:\\\Directory:\sugarizer\index.html
See previous comments.

2021-03-21 16:16 UTC, ricknjacky commented
> Okay guess that there is no CLI option in Chrome to avoid prefixing with `file:///<Directory>` ?

No, I searched for one like that, couldn't find one. Please do tell me if there is one in future 

> See my request changes below.

Committing them now. Thanks for the feedback.

2021-03-27 20:23 UTC, merged

2021-03-27 20:23 UTC, llaske commented
Nice. Thanks.