Documentation for Sugarizer IOS build
llaske/sugarizer pull request #963
Opened 2021-06-16 06:09 UTC by sarthak-g

2021-06-18 11:27 UTC, llaske requested changes
Nice. But few more things to update.
See my comments.

2021-06-18 11:27 UTC, llaske commented on docs/ios/ios_doc.md
> +
It's not enough. As mentioned [here](https://github.com/llaske/sugarizer/blob/dev/config.xml#L80), a patched version of the `cordova-plugin-wkwebview-file-xhr` is need on iOS.
So a git clone of [this repo](https://github.com/llaske/cordova-plugin-wkwebview-file-xhr) is require to generate the file.

2021-06-18 11:27 UTC, llaske commented on docs/ios/make_ios.sh
> +cordova plugin add @ahovakimyan/cordova-plugin-wkwebviewxhrfix
Should be replaced by my version. See [here](https://github.com/llaske/cordova-plugin-wkwebview-file-xhr#about-sugarizer-update) why.

2021-06-19 07:05 UTC, sarthak-g commented
@llaske , made suggested changes. Please review.

2021-06-21 15:57 UTC, merged

2021-06-21 15:57 UTC, llaske commented
Ok thanks.